# Generated by Django 3.1.5 on 2021-01-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postalcode',
            field=models.CharField(max_length=7, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='province',
            field=models.CharField(max_length=50, verbose_name='Province'),
        ),
    ]
